version: "3.4"
services:

  proxy:
    build:
      context: .
      dockerfile: envoy.Dockerfile
    # volumes:
    #   - ./envoy.yaml:/etc/envoy.yaml
    networks:
      envoymesh:
        aliases:
          - envoy
    expose:
      - "8080"
      - "9901"
    ports:
      - "8080:8080/tcp"
      - "9901:9901/tcp"

  api:
    container_name: api
    image: juliocesarmidia/http-simple-api:v1.0.0
    networks:
      envoymesh:
        aliases:
          - api-svc
    environment:
      - API_PORT="8080"
    expose:
      - "8080"
    ports:
      - "8080:8080/tcp"

networks:
  envoymesh:
    name: envoymesh
