apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: envoy
  labels:
    app: envoy

spec:
  limits:
  - default:
      memory: "256Mi"
      cpu: "400m"
    defaultRequest:
      memory: "128Mi"
      cpu: "200m"
    type: Container

# Limits:
#   cpu:     400m
#   memory:  256Mi
# Requests:
#   cpu:     200m
#   memory:  128Mi
